/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dnstoolfinal;

/**
 *
 * @author longy
 */
public class MainFrom extends javax.swing.JFrame {

    /**
     * Creates new form MainFrom
     */
    //Tạo các biến sử dụng trong chương trình
    
    //End
    public MainFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblKeNgang = new javax.swing.JLabel();
        lblSensorProperties = new javax.swing.JLabel();
        lblRadius = new javax.swing.JLabel();
        lblOffsetAngle = new javax.swing.JLabel();
        lblT0 = new javax.swing.JLabel();
        txtRadius = new javax.swing.JTextField();
        txtOffsetAngle = new javax.swing.JTextField();
        txtT0 = new javax.swing.JTextField();
        lblKeNgang1 = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        lblH = new javax.swing.JLabel();
        lblW = new javax.swing.JLabel();
        lblP = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        txtH = new javax.swing.JTextField();
        txtW = new javax.swing.JTextField();
        txtP = new javax.swing.JTextField();
        txtT = new javax.swing.JTextField();
        lblKeNgang2 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnExecute = new javax.swing.JButton();
        btnDrawNetwork = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setText("Directional Sensor Network Tool");

        lblKeNgang.setText("-----------------------------------------------------------------------------------------------------------------------------------");

        lblSensorProperties.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSensorProperties.setText("Sensor Properties");

        lblRadius.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRadius.setText("Radius(m)");

        lblOffsetAngle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblOffsetAngle.setText("Offset angle(0<x<180)");

        lblT0.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblT0.setText("LifeTime(s)");

        txtRadius.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtOffsetAngle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtT0.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblKeNgang1.setText("-----------------------------------------------------------------------------------------------------------------------------------");

        lblArea.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblArea.setText("Area");

        lblH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblH.setText("Height(m)");

        lblW.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblW.setText("Width(m)");

        lblP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblP.setText("Coverage rate(0<p<=1)");

        lblT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblT.setText("Lifetime of Network(s)");

        txtH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtW.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblKeNgang2.setText("-----------------------------------------------------------------------------------------------------------------------------------");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCalculate.setText("Calculate");

        btnExecute.setText("Execute");

        btnDrawNetwork.setText("Draw Network");
        btnDrawNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawNetworkActionPerformed(evt);
            }
        });

        txaResult.setEditable(false);
        txaResult.setColumns(20);
        txaResult.setRows(5);
        jScrollPane1.setViewportView(txaResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKeNgang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKeNgang1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblArea))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblKeNgang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSensorProperties))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblT0)
                                    .addComponent(lblRadius)
                                    .addComponent(lblOffsetAngle))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOffsetAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtT0, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblT)
                                    .addComponent(lblP)
                                    .addComponent(lblW)
                                    .addComponent(lblH))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtW, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnClear)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalculate)
                                .addGap(18, 18, 18)
                                .addComponent(btnExecute)
                                .addGap(18, 18, 18)
                                .addComponent(btnDrawNetwork)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblKeNgang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSensorProperties)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRadius)
                                    .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblOffsetAngle))
                            .addComponent(txtOffsetAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblT0))
                    .addComponent(txtT0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblKeNgang1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblArea)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblH)
                                            .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblW))
                                    .addComponent(txtW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblP))
                            .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblT))
                    .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblKeNgang2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnCalculate)
                    .addComponent(btnExecute)
                    .addComponent(btnDrawNetwork))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDrawNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawNetworkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrawNetworkActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        //Xử lý xóa toàn bộ nội dung trong các textbox và textArea
        txtH.setText((""));
        txtOffsetAngle.setText((""));
        txtP.setText((""));
        txtRadius.setText((""));
        txtT.setText((""));
        txtT0.setText((""));
        txtW.setText((""));
        txaResult.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDrawNetwork;
    private javax.swing.JButton btnExecute;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblH;
    private javax.swing.JLabel lblKeNgang;
    private javax.swing.JLabel lblKeNgang1;
    private javax.swing.JLabel lblKeNgang2;
    private javax.swing.JLabel lblOffsetAngle;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblRadius;
    private javax.swing.JLabel lblSensorProperties;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lblT0;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblW;
    private javax.swing.JTextArea txaResult;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtOffsetAngle;
    private javax.swing.JTextField txtP;
    private javax.swing.JTextField txtRadius;
    private javax.swing.JTextField txtT;
    private javax.swing.JTextField txtT0;
    private javax.swing.JTextField txtW;
    // End of variables declaration//GEN-END:variables
}
